platform :ios, '8.0'
inhibit_all_warnings!
target 'WaiMaiClient' do
    pod 'GoogleMaps', '= 2.3.0'
    pod 'PayPal-iOS-SDK'
    pod 'Stripe'
    pod 'IQKeyboardManager', '~> 5.0.6'
    pod 'AFNetworking', '~> 3.0'
    pod 'SDWebImage', '~> 3.7.5'
    pod 'MJExtension'
    pod 'MJRefresh', '~> 3.1.15.1'
end

